CRX_VERSION = 1.0
CRX_DATE = "1/3/2024" -- version date
CRX_LINK = "https://github.com/barkleygaiden/crx" -- link to CRX

CRX_USER = 2
CRX_ADMIN = 4
CRX_SUPERADMIN = 8

CRX_PARAM_BOOL = 2
CRX_PARAM_NUMBER = 4
CRX_PARAM_STRING = 8
CRX_PARAM_ENTITY = 16
CRX_PARAM_PLAYER = 32