util.AddNetworkString("CLXNetworkUserGroup")

CRX_VERSION = 1.0
CRX_DATE = "1/3/2024" -- version date
CRX_LINK = "https://github.com/barkleygaiden/crx" -- link to CRX

CRX_USER = 2
CRX_ADMIN = 4
CRX_SUPERADMIN = 8

CRX_PARAMETER_BOOL = 2
CRX_PARAMETER_NUMBER = 4
CRX_PARAMETER_STRING = 8
CRX_PARAMETER_ENTITY = 16
CRX_PARAMETER_PLAYER = 32